export const ActionType = {
    ADD_CARD: 'ADD_CARD',
    UPDATE_CARD: 'UPDATE_CARD',
    DELETE_CARD: 'DELETE_CARD',
    ADD_COLUMN: 'ADD_COLUMN',
    UPDATE_COLUMN: 'UPDATE_COLUMN',
    DELETE_COLUMN: 'DELETE_COLUMN',
};